function [minusIndex] = findEqualFun(Eccentricity, Orientation,MajorAxisLength,Area,Solidity,rMean,Centroid)
minusIndex = [];
index = find(Eccentricity >= 0.78 & ...
    Orientation >=-30 & Orientation <=25 &...
    MajorAxisLength <= 100&...
    Area >= 80 &...
    Solidity >= 0.72 &...
    (rMean - Centroid(:,2))' < 20); % 15
N = length(index);
if 1%N == 6
    minusIndex = index;
end
end