function [minusIndex] = findEqualFun(Eccentricity, Orientation,MajorAxisLength,Area,Solidity)
minusIndex = [];
index = find(Eccentricity >= 0.85 & ...
    Orientation >=-30 & Orientation <= 16.5 &...
    MajorAxisLength <= 100&...
    Area >= 100 &...
    Solidity >= 0.72 );
N = length(index);
if 1%N == 6
    minusIndex = index;
end
end